# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jaskier_msgs/fingerADC.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class fingerADC(genpy.Message):
  _md5sum = "684db9cd25303adefa48e14d9ffba24a"
  _type = "jaskier_msgs/fingerADC"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ADC values for each finger joint, and the min and max of seen adc vals

# The order is thumb, index, middle, ring, little
int32[5] adcVals
int32 adcMin
int32 adcMax
"""
  __slots__ = ['adcVals','adcMin','adcMax']
  _slot_types = ['int32[5]','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       adcVals,adcMin,adcMax

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(fingerADC, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.adcVals is None:
        self.adcVals = [0] * 5
      if self.adcMin is None:
        self.adcMin = 0
      if self.adcMax is None:
        self.adcMax = 0
    else:
      self.adcVals = [0] * 5
      self.adcMin = 0
      self.adcMax = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_5i().pack(*self.adcVals))
      _x = self
      buff.write(_get_struct_2i().pack(_x.adcMin, _x.adcMax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 20
      self.adcVals = _get_struct_5i().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.adcMin, _x.adcMax,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.adcVals.tostring())
      _x = self
      buff.write(_get_struct_2i().pack(_x.adcMin, _x.adcMax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 20
      self.adcVals = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=5)
      _x = self
      start = end
      end += 8
      (_x.adcMin, _x.adcMax,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
