# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jaskier_msgs/tipCoords.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class tipCoords(genpy.Message):
  _md5sum = "16c13f95c15ab83cb390e0132a0d1f39"
  _type = "jaskier_msgs/tipCoords"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# stores fingertip coordinates

float64[3] thumb
float64[3] index
float64[3] middle
float64[3] ring
float64[3] little
"""
  __slots__ = ['thumb','index','middle','ring','little']
  _slot_types = ['float64[3]','float64[3]','float64[3]','float64[3]','float64[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       thumb,index,middle,ring,little

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(tipCoords, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.thumb is None:
        self.thumb = [0.] * 3
      if self.index is None:
        self.index = [0.] * 3
      if self.middle is None:
        self.middle = [0.] * 3
      if self.ring is None:
        self.ring = [0.] * 3
      if self.little is None:
        self.little = [0.] * 3
    else:
      self.thumb = [0.] * 3
      self.index = [0.] * 3
      self.middle = [0.] * 3
      self.ring = [0.] * 3
      self.little = [0.] * 3

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_3d().pack(*self.thumb))
      buff.write(_get_struct_3d().pack(*self.index))
      buff.write(_get_struct_3d().pack(*self.middle))
      buff.write(_get_struct_3d().pack(*self.ring))
      buff.write(_get_struct_3d().pack(*self.little))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 24
      self.thumb = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.index = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.middle = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.ring = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.little = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.thumb.tostring())
      buff.write(self.index.tostring())
      buff.write(self.middle.tostring())
      buff.write(self.ring.tostring())
      buff.write(self.little.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 24
      self.thumb = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.index = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.middle = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.ring = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.little = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
