// Generated by gencpp from file jaskier_msgs/touchContact.msg
// DO NOT EDIT!


#ifndef JASKIER_MSGS_MESSAGE_TOUCHCONTACT_H
#define JASKIER_MSGS_MESSAGE_TOUCHCONTACT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaskier_msgs
{
template <class ContainerAllocator>
struct touchContact_
{
  typedef touchContact_<ContainerAllocator> Type;

  touchContact_()
    {
    }
  touchContact_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::jaskier_msgs::touchContact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaskier_msgs::touchContact_<ContainerAllocator> const> ConstPtr;

}; // struct touchContact_

typedef ::jaskier_msgs::touchContact_<std::allocator<void> > touchContact;

typedef boost::shared_ptr< ::jaskier_msgs::touchContact > touchContactPtr;
typedef boost::shared_ptr< ::jaskier_msgs::touchContact const> touchContactConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaskier_msgs::touchContact_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaskier_msgs::touchContact_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace jaskier_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jaskier_msgs::touchContact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaskier_msgs::touchContact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaskier_msgs::touchContact_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaskier_msgs::touchContact_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaskier_msgs::touchContact_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaskier_msgs::touchContact_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaskier_msgs::touchContact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::jaskier_msgs::touchContact_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::jaskier_msgs::touchContact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaskier_msgs/touchContact";
  }

  static const char* value(const ::jaskier_msgs::touchContact_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaskier_msgs::touchContact_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Indicates which fingertips are touching and the proximity of the contact\n"
"\n"
"# TODO: determine how to store finger touch data\n"
;
  }

  static const char* value(const ::jaskier_msgs::touchContact_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaskier_msgs::touchContact_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct touchContact_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaskier_msgs::touchContact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::jaskier_msgs::touchContact_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // JASKIER_MSGS_MESSAGE_TOUCHCONTACT_H
