// Generated by gencpp from file jaskier_msgs/ultraTimeStamp.msg
// DO NOT EDIT!


#ifndef JASKIER_MSGS_MESSAGE_ULTRATIMESTAMP_H
#define JASKIER_MSGS_MESSAGE_ULTRATIMESTAMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jaskier_msgs
{
template <class ContainerAllocator>
struct ultraTimeStamp_
{
  typedef ultraTimeStamp_<ContainerAllocator> Type;

  ultraTimeStamp_()
    : stamp()  {
    }
  ultraTimeStamp_(const ContainerAllocator& _alloc)
    : stamp()  {
  (void)_alloc;
    }



   typedef boost::array<ros::Time, 5>  _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> const> ConstPtr;

}; // struct ultraTimeStamp_

typedef ::jaskier_msgs::ultraTimeStamp_<std::allocator<void> > ultraTimeStamp;

typedef boost::shared_ptr< ::jaskier_msgs::ultraTimeStamp > ultraTimeStampPtr;
typedef boost::shared_ptr< ::jaskier_msgs::ultraTimeStamp const> ultraTimeStampConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator1> & lhs, const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator1> & lhs, const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jaskier_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1937f5302cea0024ac517264ca4dda57";
  }

  static const char* value(const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1937f5302cea0024ULL;
  static const uint64_t static_value2 = 0xac517264ca4dda57ULL;
};

template<class ContainerAllocator>
struct DataType< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jaskier_msgs/ultraTimeStamp";
  }

  static const char* value(const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timestamps for ultrasonic module\n"
"# [0] - when tx pulse is sent\n"
"# [1-4] - when rx detects pulse\n"
"\n"
"time[5] stamp\n"
;
  }

  static const char* value(const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultraTimeStamp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jaskier_msgs::ultraTimeStamp_<ContainerAllocator>& v)
  {
    s << indent << "stamp[]" << std::endl;
    for (size_t i = 0; i < v.stamp.size(); ++i)
    {
      s << indent << "  stamp[" << i << "]: ";
      Printer<ros::Time>::stream(s, indent + "  ", v.stamp[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JASKIER_MSGS_MESSAGE_ULTRATIMESTAMP_H
