# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  imu_x:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  imu_y:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  imu_z:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  index_dip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  index_mcp:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  index_pip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  little_dip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  little_mcp:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  little_pip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  middle_dip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  middle_mcp:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  middle_pip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ring_dip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ring_mcp:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ring_pip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_ip:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_mcp:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ultra_x:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ultra_y:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0
  ultra_z:
    has_velocity_limits: true
    max_velocity: 20
    has_acceleration_limits: false
    max_acceleration: 0